name: campsite
description: "A scalable campsite platform for hosts and guests."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.0.5

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Data & Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # HTTP Client
  dio: ^5.4.0

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.3.6
  geocoding: ^3.0.0
  maps_launcher: ^3.0.0+1

  # Utilities
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  locale_names: ^1.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  # Testing
  mockito: ^5.4.4

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/campsite.png"
  image_path: "assets/images/campsite.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/campsite.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
