name: campsite
description: "A scalable campsite platform for hosts and guests."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  google_fonts: ^6.2.1

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Data & Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # HTTP Client
  dio: ^5.4.0

  # Maps
  google_maps_flutter: ^2.5.3
  google_maps_cluster_manager: ^3.0.0+1
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

  # Utilities
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
